### ISSUE TITLE
No such var: fs/xdg-data-home when trying specific dep

### ISSUE THREAD

**Issue by jeroenvandijk** [eval/deps-try#23]
Thank you for your work Gert! :)

Found a small issue with a specific repo that I wanted to try. I wanted to try [Squint](https://github.com/squint-cljs/squint) and I found a weird interaction with the `babashka/fs` dependency. A work around is to add the dep manually (`deps-try babashka/fs io.github.squint-cljs/squint`). I don't see yet what the cause is though. A shell session below.

(FYI, I installed `deps-try` via `bbin install io.github.eval/deps-try`, works fine, after finding the error I also tried the other ways, but that was not it).

Shell session:
```
➜ bb version
babashka v1.3.184

➜ deps-try -v
deps-try-dev v0.8.0

➜ deps-try io.github.squint-cljs/squint
Syntax error compiling at (eval/deps_try/try.clj:115:30).
No such var: fs/xdg-data-home

Full report at:
/var/folders/2w/4mynsgjs28j637qzqkxt1lsr0000gn/T/clojure-8442043964243317078.edn

➜ deps-try babashka/fs io.github.squint-cljs/squint

[Rebel readline] Type :repl/help for online help info
user=> (require 'squint.compiler)
WARNING: *repl* already refers to: #'clojure.core/*repl* in namespace: squint.compiler-common, being replaced by: #'squint.compiler-common/*repl*
nil
user=> (squint.compiler/compile-string (pr-str '(fn [e] "hello")))
"import * as squint_core from 'squint-cljs/core.js';\nfunction (e) {\nreturn \"hello\";\n};\n"
user=>
```

**Comment by eval** [comment]
Hey @jeroenvandijk, thanks for bringing this up! This should be fixed on unstable/v0.9.0-pre.1
